# Generated by Django 5.1.2 on 2024-10-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PubMedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('pmid', models.CharField(max_length=50, unique=True)),
                ('title', models.TextField()),
                ('pubdate', models.DateField()),
                ('abstract', models.TextField()),
            ],
        ),
    ]
