# Generated by Django 5.1.2 on 2024-11-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubmedarticle',
            name='pubdate',
            field=models.CharField(max_length=20),
        ),
    ]
